services:
  teleport-et-demo:
    build: .
    hostname: teleport-et-container
    image: teleport-et:local
    labels:
      kompose.image-pull-policy: "IfNotPresent"
      kompose.service.type: "NodePort"
    environment:
      TELEPORT_ADDRESS: "${TELEPORT_ADDRESS}"
      TELEPORT_JOIN_TOKEN: "${TELEPORT_JOIN_TOKEN}"
      ENVIRONMENT_TAG: "${ENVIRONMENT_TAG}"
    ports:
      - "2222:22"   # SSHD
      - "2022:2022" # Eternal Terminal
    #restart: unless-stopped